In [1]:
import numpy as np

# Creation

In [7]:
some_list = list(range(0, 10, 1))
one_dimension = np.array(some_list)
print(f'type: {type(one_dimension)}\nelements: {one_dimension}')

type: <class 'numpy.ndarray'>
elements: [0 1 2 3 4 5 6 7 8 9]


### Vectorized Operation

In [8]:
doubled_one_dimension = 2 * one_dimension
doubled_some_list = 2 * some_list
print(f'numpy case: {doubled_one_dimension}\nlist case: {doubled_some_list}')

numpy case: [ 0  2  4  6  8 10 12 14 16 18]
list case: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### N-Dimensional ARRAY [ndarray]

In [12]:
two_dimention = np.array([[1, 2, 3], [4, 5, 6]])
print(f'len: ({len(two_dimention)} X {len(two_dimention[0])})\nelements: \n{two_dimention}')

len: (2 X 3)
elements: 
[[1 2 3]
 [4 5 6]]


### Array Info

In [13]:
sample_array = np.array([[1, 2, 3], [4, 5, 6]])
print(f'ndim: {sample_array.ndim}\nshape:\n{sample_array.shape}')

ndim: 2
shape:
(2, 3)


# Search

## Indexing

In [14]:
sample_array = np.array([[1, 2, 3], [4, 5, 6]])
sample_array[0, 2]

3

## Slicing

In [15]:
sample_array = np.array([[1, 2, 3], [4, 5, 6]])
sample_array[:, 2]

array([3, 6])

### Fancy Indexing

In [16]:
sample_array = np.array([[1, 2, 3], [4, 5, 6]])
sample_filter_array = np.array([[False, False, True], [True, True, False]])
sample_array[sample_filter_array]

array([3, 4, 5])

In [18]:
sample_array % 2 == 0

array([[False,  True, False],
       [ True, False,  True]])

In [19]:
sample_array[sample_array % 2 == 0]

array([2, 4, 6])

In [20]:
sample_array = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
sample_filter_array = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
sample_array[sample_filter_array]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [21]:
sample_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
sample_array[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [22]:
1166880 + 1484711 + 674456 + 444169 + 33739 + 17904

3821859

In [23]:
301954 + 122639 + 264020 + 165209

853822